### ISSUE TITLE
DLC Pin Data & Ethernet Example

### ISSUE THREAD

**Issue by philipneill** [DiagProf/ISO22900.II#1]
Hi DiagProf,

really appreciating your work here! :) 
This helps a lot to get a Diagnostics Tool VCI independent.

Can you tell me what the DLC Pin Data means, because when i connect a Vector Interface it always fails because of that.

And also an Ethernet Sample would be really helpful for my Application.

Thank you so much for all your great work here! :)

Best Regards,

Philip

**Comment by DiagProf** [comment]
Hi Philip,
i'm a bit busy so I'll try to answer with bullet points.

- Please do not forget that most manufacturers (including Vector) check the license during OpenComLogicalLink (ISO22900-2 -> PDUCreateComLogicalLink). I hope you have a license from Vector, otherwise nothing goes on. (That's why I like Softing, the license is already included with Softing interfaces)
- DLC is Data link connector (a term also used in ODX)  https://en.wikipedia.org/wiki/Data_link_connector_(automotive)
- DLC Pin Data now combines the PIN with a physical signal that should come out of this pin. The possible signals are specified in ISO 22900-2 or in ODX. 
![image](https://user-images.githubusercontent.com/56319388/164056598-de3f3c9d-8364-4929-b7c7-2e4f441ee982.png)

- As an example, most manufacturers have CAN high and CAN low on DLC PIN 6 and 14. Therefore  var dlcPinData = new Dictionary<uint, string> { { 6, "HI" }, { 14, "LOW" } };  and forCAN it self var busTypeName = "ISO_11898_2_DWCAN";  (DW -> dual wire)
- But now there is no real DLC plug on the interface on the Vector. Now you could try with 2 and 7  { { 7, "HI" }, { 2, "LOW" } } but I would recommend you to read the documentation "Vector D-PDU API Installation and Quick Start Guide.pdf". And then I always do the trick with the registry entry. 
![image](https://user-images.githubusercontent.com/56319388/164058691-3cb651b4-8907-4b28-af71-d4de5243e742.png)
With this you can pretend that the Vector interface has a DLC (OBD2 connector). The good thing is that the code then runs without any changes, even with most other VCIs. 

I do all my stuff with real ECUs. Unfortunately I don't have a DoIP ECU here. As soon as I get one I'll create the example.

but like this:
                    //DoIP Setup Pin8->activation Pull-Up mostly mechanically hardwired
                    var dlcPinData = new Dictionary<uint, string> { { 3, "RX" }, { 11, "MINUS" }, { 12, "TX" }, { 13, "LOW" }};
                    var busTypeName = "IEEE_802_3";
                    var protocolName = "ISO_14229_5_on_ISO_13400_2";

But the ApiOne still lacks IOCTL for DoIP.
Also what I would do if someone gave me a DoIP ECU.

Best Regards,
Jörg

**Comment by WSorban** [comment]
Hello Jörg,

I really wanted to take an opportunity and thank you for this very well made library!!!

I have successfully integrated and tested it, and now the program is in production, with the replaced PDU API library.
However, my application is done in .NET 4.7.2, so I had to do some changes to it, and it now became a bit different from the git source, and so, it would be challenging for me to contribute with code.

However, I would like to find some other means to help back, so if I can donate, and you can accept a DoIP hardware, I would be more than happy to send one your way.

Would you write here a way, where we could arrange for the shipping?

Or you can contact me directly by email to wsorban@gmail.com or WhatsApp at +40 7 4321 1234

Best regards,
Wilhelm

**Comment by philipneill** [comment]
Hello Jörg,

Thank you so much for your fast reply!
Now i understand the things a bit more and yes i forgot to use the license for the Vector Interface 👍 

If Wilhelm can't provide you with an DoIP ECU, i would talk with my company about it.
With the dlcPinData you provided it now fails at the OpenComLogicalLink again, but for the first step CAN will work fine.

Thank you so much for the ApiWrapper and your help, really appreciating it :)

Best Regards,

Philip

**Comment by DiagProf** [comment]
DoIP should work for quite a while. I just forgot to close this. :-)
